# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Ubuntu 22.04
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/jammy64"
    ubuntu.vm.hostname = "ubuntu-wordpress"
    ubuntu.vm.network "private_network", ip: "192.168.56.10"
    ubuntu.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  # CentOS 10
  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/stream10"
    centos.vm.hostname = "centos-wordpress"
    centos.vm.network "private_network", ip: "192.168.56.11"
    centos.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  # SHELL
  config.vm.provision "shell", path: "scripts/add_ssh_key.sh"

end