apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  root_password: {{ .Values.mysql.rootPassword }}
  database: {{ .Values.mysql.database }}
  user: {{ .Values.mysql.user }}
  password: {{ .Values.mysql.password }}