# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.define "server" do |server|
    server.vm.box = "bento/ubuntu-20.04"
    server.vm.box_check_update = false
    server.vm.provider "virtualbox" do |vb|
      vb.name = "server"
      vb.gui = false
      vb.memory = "1024"
    end
    server.vm.hostname = "server"
    server.vm.network "public_network", ip: "192.168.21.103"
    server.vm.provision "shell", path: "./script/server.sh"
  end

  config.vm.define "client" do |client|
    client.vm.box = "bento/ubuntu-20.04"
    client.vm.box_check_update = false
    client.vm.provider "virtualbox" do |vb|
      vb.name = "client"
      vb.gui = false
      vb.memory = "1024"
    end
    client.vm.hostname = "client"
    client.vm.network "public_network", ip: "192.168.21.104"
    client.vm.provision "shell", path: "./script/client.sh"
  end

end
