- name: PyMySQL | Install pip
  package:
    name: python3-pip
    state: present
  become: true

- name: PyMySQL | Install packaging 
  raw: '/usr/bin/python3 -m pip install packaging'
  become: true
  
- name: PyMySQL | Install
  pip:
    name: PyMySQL
    executable: pip3
  become: true
  