# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.define "server" do |server|
    server.vm.box = "bento/ubuntu-20.04"
    server.vm.box_check_update = false
    server.vm.hostname = "server"
    server.vm.network "public_network", ip: "192.168.21.100"
  end

  config.vm.define "client" do |client|
    client.vm.box = "bento/ubuntu-20.04"
    client.vm.box_check_update = false
    client.vm.hostname = "client"
    client.vm.network "public_network", ip: "192.168.21.101"
    client.vm.provision "shell", path: "./script/server.sh"
  end

end
