# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "dev" do |dev|
    dev.vm.box = "ubuntu/focal64"
    dev.vm.box_check_update = false
    dev.vbguest.auto_update = false
    dev.vm.hostname = "dev"
    dev.vm.network "private_network", ip: "192.168.56.10"
    dev.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  end

  config.vm.define "prod" do |prod|
    prod.vm.box = "ubuntu/focal64"
    prod.vm.box_check_update = false
    prod.vbguest.auto_update = false
    prod.vm.hostname = "prod"
    prod.vm.network "private_network", ip: "192.168.56.20"
    prod.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  end
end