pipeline {
    agent any
    tools {
        maven 'maven-3'
    }

    stages {
        stage('Detect Changes in target apps') {
            steps {
                script {
                    // Получаем список изменённых файлов
                    changedFiles = sh(
                        script: "git diff --name-only HEAD~1 HEAD",
                        returnStdout: true
                    ).trim().split('\n')

                    echo "Changed files: ${changedFiles}"

                    // Определяем какие приложения изменены
                    apps = [
                        "app-World",
                        "app-Jenkins",
                        "app-Devops"
                    ]

                    changedApps = []

                    for (app in apps) {
                        if (changedFiles.any { it.startsWith("lesson26/${app}/") }) {
                            changedApps << app
                        }
                    }

                    echo "Changed apps: ${changedApps}"
                }
            }
        }
    }
}