{{- if .Values.wordpress.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.wordpress.name }}-hpa
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.wordpress.name }}
  minReplicas: {{ .Values.wordpress.hpa.minReplicas }}
  maxReplicas: {{ .Values.wordpress.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.wordpress.hpa.targetCPUUtilizationPercentage }}
{{- end }}