apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.wordpress.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  user: {{ .Values.wordpress.user }}
  password: {{ .Values.wordpress.password }}