{
 "title": "Lesson 29",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Общее число запросов к ui по путям / и /new",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ui_request_count{job=\"blackbox-ui\", path=\"/\"}",
     "legendFReddit Appormat": "__auto"
    },
    {
     "expr": "ui_request_count{job=\"blackbox-ui\", path=\"/new\", method=\"POST\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Трафик (скорость изменения) запросов к ui по путям / и /new",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_total{job=\"blackbox-ui\", path=\"/\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_server_requests_total{job=\"blackbox-ui\", path=\"/new\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "90й процентиль времени ответа на запросы",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "quantile(0.9, sum by(le) (rate(ui_request_response_time_bucket{job=\"blackbox-ui\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}