apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: {{ .Values.StorageClass.name }}
  namespace: {{ .Values.namespace }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer